import StyledComponentsRegistry from "@/app/regystry";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import GlobalStyles from "@/styles/global";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <StyledComponentsRegistry>
        <GlobalStyles />
        <Header />
        {children}
        <Footer />
      </StyledComponentsRegistry>
    </html>
  );
}
