import type { Metadata } from "next";
import GlobalStyles from "@/styles/global";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/app/regystry";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <StyledComponentsRegistry>
        <GlobalStyles />
        <Footer />
        <Header />
        {children}
      </StyledComponentsRegistry>
    </html>
  );
}
